#pragma once

typedef enum {
  STATUS_SUCCESS,
  STATUS_ERROR,
  STATUS_ERRNO_ERROR,
  STATUS_BAD_ALLOC,
  STATUS_OVERFLOW,
  STATUS_UNDERFLOW,
  STATUS_NOT_FOUND,
  STATUS_ERROR_SIGNAL,
  STATUS_UNDEFINED
} TnStatus;